### ISSUE TITLE
Add initialiser to initialise system

### ISSUE THREAD

**Issue by slaymuel** [TeamOverkill/md#1]
Set up atomic coordinates.
1. Assign random coordinates.
2. Randomly displace each atom iteratively until there is no overlap

**Comment by SHervoe-Hansen** [comment]
3. Assign random velocities according to the Maxwell-Boltzmann distribution, which depends on a) target/reference temperature b) mass of the individual particles.

**Comment by slaymuel** [comment]
Done!
