### ISSUE TITLE
Minimisation option

### ISSUE THREAD

**Issue by SHervoe-Hansen** [TeamOverkill/md#9]
A minimisation program may be required in order to fix bad contacts in the initial configuration. I suggest we just utilise steepest decent for this. This can already be seen for the magnetic particle system with Anderson thermostat.

**Comment by slaymuel** [comment]
Added a simple minimisation which removes overlap between atoms at the start of a simulation. I suggest we skip the "real" minimisation until we have properly determined that we really need it.
